#!/bin/bash

# 🎯 COMMANDES EXACTES - Correction HTTP 401
# Ce script affiche les commandes à exécuter (ne les exécute pas automatiquement)

echo "════════════════════════════════════════════════════════════"
echo "🎯 CORRECTION HTTP 401 - Commandes à exécuter"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📋 ÉTAPE 1 : Vérifier la structure du projet"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Exécutez cette commande pour trouver l'Edge Function :"
echo ""
echo "  find . -name 'index.ts' -path '*/send-support-email/*' 2>/dev/null"
echo ""
echo "OU"
echo ""
echo "  find . -name '*send-support-email*.ts' 2>/dev/null"
echo ""
echo "Résultat attendu :"
echo "  ./supabase/functions/send-support-email/index.ts"
echo ""
echo "─────────────────────────────────────────────────────────────"
read -p "Appuyez sur Entrée quand c'est fait..."
echo ""

echo "════════════════════════════════════════════════════════════"
echo "📋 ÉTAPE 2 : Vérifier la connexion Supabase"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Exécutez :"
echo ""
echo "  supabase projects list"
echo ""
echo "Si erreur 'not logged in' :"
echo ""
echo "  supabase login"
echo ""
echo "─────────────────────────────────────────────────────────────"
read -p "Appuyez sur Entrée quand c'est fait..."
echo ""

echo "════════════════════════════════════════════════════════════"
echo "📋 ÉTAPE 3 : Vérifier RESEND_API_KEY"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Exécutez :"
echo ""
echo "  supabase secrets list"
echo ""
echo "Si RESEND_API_KEY n'apparaît pas :"
echo ""
echo "  supabase secrets set RESEND_API_KEY=re_VOTRE_VRAIE_CLE"
echo ""
echo "⚠️  Remplacez 're_VOTRE_VRAIE_CLE' par votre clé Resend réelle !"
echo ""
echo "─────────────────────────────────────────────────────────────"
read -p "Appuyez sur Entrée quand c'est fait..."
echo ""

echo "════════════════════════════════════════════════════════════"
echo "🚀 ÉTAPE 4 : DÉPLOYER avec correction"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✨ COMMANDE PRINCIPALE (copier-coller) :"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "supabase functions deploy send-support-email --no-verify-jwt"
echo "────────────────────────────────────────────────────────────"
echo ""
echo "Cette commande :"
echo "  ✅ Déploie l'Edge Function"
echo "  ✅ Désactive la vérification JWT (verify_jwt = false)"
echo "  ✅ Corrige le problème HTTP 401"
echo ""
echo "Résultat attendu :"
echo "  ✓ Deployed Function send-support-email"
echo ""
echo "─────────────────────────────────────────────────────────────"
read -p "Appuyez sur Entrée APRÈS avoir exécuté le déploiement..."
echo ""

echo "════════════════════════════════════════════════════════════"
echo "✅ ÉTAPE 5 : Vérifier le déploiement"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Exécutez :"
echo ""
echo "  supabase functions list"
echo ""
echo "Vous devriez voir :"
echo "  send-support-email | deployed | [version] | [date récente]"
echo ""
echo "─────────────────────────────────────────────────────────────"
read -p "Appuyez sur Entrée quand c'est vérifié..."
echo ""

echo "════════════════════════════════════════════════════════════"
echo "🧪 ÉTAPE 6 : Tester"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Test 1 : Créer un ticket depuis l'app iOS"
echo "  1. Lancer l'app Store Immo"
echo "  2. Se connecter"
echo "  3. Aller dans : Compte → Signaler un problème"
echo "  4. Remplir et envoyer un ticket"
echo ""
echo "Test 2 : Vérifier les logs"
echo "  Exécutez :"
echo ""
echo "    supabase functions logs send-support-email --tail 20"
echo ""
echo "  Résultat attendu :"
echo "    ✅ Email envoyé avec succès"
echo ""
echo "  Résultat PAS attendu (erreur corrigée) :"
echo "    ❌ UNAUTHORIZED_NO_AUTH_HEADER"
echo ""
echo "Test 3 : Vérifier l'email"
echo "  Ouvrir : support@storeimmo.com"
echo "  Email attendu avec le sujet : [Ticket Support] ..."
echo ""
echo "Test 4 : Vérifier dans Resend"
echo "  Aller sur : https://resend.com/emails"
echo "  Statut attendu : Delivered"
echo ""
echo "─────────────────────────────────────────────────────────────"
read -p "Appuyez sur Entrée après avoir testé..."
echo ""

echo "════════════════════════════════════════════════════════════"
echo "✅ RÉCAPITULATIF"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Commande de correction utilisée :"
echo ""
echo "  supabase functions deploy send-support-email --no-verify-jwt"
echo ""
echo "Modifications apportées :"
echo "  ✅ Edge Function : verify_jwt = false (seul changement)"
echo "  ❌ Code de la fonction : INCHANGÉ"
echo "  ❌ Trigger PostgreSQL : INCHANGÉ"
echo "  ❌ Table support_tickets : INCHANGÉE"
echo "  ❌ Application iOS : INCHANGÉE"
echo "  ❌ Configuration Resend : INCHANGÉE"
echo "  ❌ OVH : INCHANGÉ"
echo ""
echo "Statut du déploiement :"

# Vérifier si la fonction existe
if command -v supabase &> /dev/null; then
    if supabase functions list 2>/dev/null | grep -q "send-support-email"; then
        echo "  ✅ DÉPLOYÉ (vérifié)"
    else
        echo "  ⚠️  À déployer (exécutez la commande ci-dessus)"
    fi
else
    echo "  ⚠️  Supabase CLI non détecté"
fi

echo ""
echo "════════════════════════════════════════════════════════════"
echo "🎉 CORRECTION TERMINÉE"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Le problème HTTP 401 (UNAUTHORIZED_NO_AUTH_HEADER) a été"
echo "corrigé en désactivant la vérification JWT pour l'Edge"
echo "Function send-support-email."
echo ""
echo "Le trigger PostgreSQL peut maintenant appeler la fonction"
echo "sans JWT utilisateur. ✅"
echo ""
